### ISSUE TITLE
Implementing as Primary Application

### ISSUE THREAD

**Issue by MRIIOT** [SeppPenner/SparkplugNet#6] opened 2021-10-01 01:58 UTC
What is known to be missing in order to build a SpB Primary Application on top of the library?

**Comment by SeppPenner** [comment] 2021-10-04 17:26
Well, I hope nothing to be honest :D

**Comment by SeppPenner** [comment] 2021-10-08 18:21
> Something I noticed is that the metrics have to been known ahead of time by the application. Sending new metrics from nodes, ends up in here:
> 
> https://github.com/SeppPenner/SparkplugNet/blob/ed77d8aec6489af663f9578b2e3516b82dfff293/src/SparkplugNet/Core/Application/SparkplugApplicationBase.cs#L568

I assumed that this was intended within Sparkplug...

**Comment by MRIIOT** [comment] 2021-10-09 13:32
It's probably implementation specific, but I would expect arbitrary nodes and devices to connect to the primary application without any previous knowledge.

**Comment by SeppPenner** [comment] 2022-02-08 16:13
Sorry for the late reply. I will check this within the next days and provide an update.

**Comment by SeppPenner** [comment] 2022-03-13 15:46
I will close this now, since I believe this is according to the standard. If anyone has more information or clearification, just contact me here, please :)

**Closed by SeppPenner** 2022-03-13 15:46 UTC
Labels: question

**Comment by MRIIOT** [comment] 2022-03-13 16:36
> I will close this now, since I believe this is according to the standard. If anyone has more information or clearification, just contact me here, please :)

That's fine.  Once I have more time, I will re-open this with examples.
